server.port=8080
spring.application.name=BankingApp
spring.datasource.url=jdbc:postgresql://localhost:5432/eBank
spring.datasource.username=postgres
spring.datasource.password=postgre_sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
